---
- name: Проверка захвата вывода с помощью регистра
  hosts: test
  tasks:
    - name: Запуск команды
      command: uptime
      register: server_uptime

    - name: Проверяю переменную server_uptime
      debug:
        var: server_uptime

    - name: Server uptime =
      debug:
        msg: "{{ server_uptime.stdout }}"
